config/routes.rb
Rails.application.routes.draw do
  get 'home/top'
  get 'home/about'
  resources :users
  resources :posts
  root 'home#top'
  get 'about' => 'home#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to @post
  end

  def edit
    @post = Post.find(params[:id])
  end

  private
  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to posts_path
  end

  def edit
  end

  def login
    @user = User.find(params[email: params[:email], password: params[:password]])
  end
  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<h1>Circleとは</h1>
<p>毎日日報を書くためのアプリケーションです。</p>

app/views/home/top.html.erb
<h1>Circle</h1>
<p></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TkuCircle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
      <div class="container">
        <%= link_to("TweetApp", root_path, class: "navbar-brand" ) %>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="ナビゲーションの切替">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to("TweetAppとは", about_path, class: "nav-link") %>
              <%= link_to("新規投稿", new_post_path, class: "nav-link") %>
              <%= link_to "投稿一覧", posts_path, class:"nav-link"  %>
              <%= link_to "user", users_path, class:"nav-link" %>
              <%= link_to "新規登録", new_user_path, class:"nav-link" %>
            </li>
          </ul>
        </div>     
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="article">
      <% @posts.each do |post| %>
      <%= link_to  post.body, post_path(post) %>
      <% end %>
    </div> 
  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>投稿</h1>
    <%= form_with model: @post, local: true do |form| %>
    <div class="form-group">
        <%= form.label "本文" %>
        <%= form.text_area :body, class: "form-control" %>
      </div>
      <%= form.submit '登録する', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<div class="row"> 
  <div class="col-md-8">
    <% @users.each do |user| %>
      <h2>ユーザー名<%= user.name  %></h2>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>新規ユーザー登録</h1>
    <%= form_with model: @user, local: true do |form| %>
      <div class="form-group">
        <%= form.label "ユーザー名" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label "E-mail" %>
        <%= form.text_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :password,"パスワード" %>
        <%= form.password_field :password, class: "form-control" %>
      </div>
      <%= form.submit '登録する', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>